### PR TITLE
add quant_report rule, make barcode rank plot

### PR DESCRIPTION
**Pull request by mikecuoco**

### CODE REVIEW

**Comment by mikecuoco** [comment]
TODO: 

1. Show which barcodes were filtered and which weren't in rank plot
2. Make barplots across runs of each feature from `Summary.csv` STARsolo output 
3. Make rank plot for IRescue output

**Comment by jjjoelle** [comment]
Questions: 
For 1 -- the current filtering line is `plot_df["total_counts"] = plot_df.loc[plot_df["total_counts"] > 0, :]`. Would the barcodes displayed be the ones that don't make it from that line (potentially with a number greater than 0) or should they be the ones filtered out in filter.py.ipynb/filter rule? I know we were talking about raw data in rank plots but then which barcodes should be displayed?

**Comment by mikecuoco** [comment]
> Questions: For 1 -- the current filtering line is `plot_df["total_counts"] = plot_df.loc[plot_df["total_counts"] > 0, :]`. Would the barcodes displayed be the ones that don't make it from that line (potentially with a number greater than 0) or should they be the ones filtered out in filter.py.ipynb/filter rule? I know we were talking about raw data in rank plots but then which barcodes should be displayed?

The "filtered" barcodes I was referring to here are the barcodes that are identified as non-empty by STARsolo. We conduct additional filtering in the `filter.py.ipynb/filter` rule, but that is downstream of `quant_report` and should not be considered. 

Using the filtered and raw barcodes from STARsolo, try to replicate the Barcode Rank Plot shown here https://support.10xgenomics.com/single-cell-gene-
expression/software/pipelines/latest/output/summary

**Comment by jjjoelle** [comment]
Would the STARSolo output be downstream of `quant_report.ipynb` then? And for # 2 should I make a plot for every `summary.csv` found in` results>map_count>a/etc>outsGene/outsGeneFull/etc>summary.csv` (or whichever directories applicable based on snakemake config)? If so, should I do a plot per feature across all runs (i.e Number of reads: a=61415, b=61599) or a plot with all features per run?

**Comment by mikecuoco** [comment]
`quant_report`'s input is the output of `STARsolo`, thus`STARsolo` lies upstream of `quant_report`.

You should plot every value in `summary.csv` for each run separately. Perhaps you could have `quant_report` run once for each run, rather than once for all the runs.

**Pull request merged**
